stages:
  preprocess:                # name of the stage
    # wdir: t1_confection
    cmd: python -u t1_confection/B1_Run_Compiler.py
    deps:
      # files
      - t1_confection/B1_Compiler.py
      - t1_confection/MOMF_T1_A.yaml

      # folder with data
      - t1_confection/A1_Outputs/
      - t1_confection/A2_Extra_Inputs/
    outs:
      # files
      - t1_confection/A2_Structure_Lists.xlsx

      # folder with data 
      - t1_confection/A2_Output_Params/

  executing:                     # name of the stage
    # wdir: t1_confection
    cmd: python -u t1_confection/B2_Executing_OG_Model.py
    deps:
      # files
      - t1_confection/MOMF_T1_AB.yaml
      - t1_confection/osemosys_fast_preprocessed.txt
      - concatenate_files/concatenate_relac.py

      # folder with data 
      - t1_confection/A2_Output_Params/
      - t1_confection/Miscellaneous/

    outs:
      # folder with data (with cache)
      - t1_confection/Executables/

      # files (without cache)
      - t1_confection/RELAC_TX_Inputs.csv:
          cache: false
      - t1_confection/RELAC_TX_Inputs_fecha.csv:
          cache: false
      - t1_confection/RELAC_TX_Outputs.csv:
          cache: false
      - t1_confection/RELAC_TX_Outputs_fecha.csv:
          cache: false
      - t1_confection/RELAC_TX_Combined_Inputs_Outputs.csv:
          cache: false
      - t1_confection/RELAC_TX_Combined_Inputs_Outputs_fecha.csv:
          cache: false

      # folder with data (without cache)
      - t1_confection/A2_Outputs_Params_otoole/:
          cache: false